### Create Link

POST http://localhost:3000/api/users/register

{
    "name" : "Jordan",
    "email":"jordan@gmail.com",
    "password": "admin123"
}

### Login User

POST http://localhost:3000/api/users/login

{
    "email":"jordan@gmail.com",
    "password": "admin123"
}

