### Create link

POST http://localhost:3000/api/links

{
    "name" : "ProductX",
    "slug":"product-x"
}

### Get user's links

GET http://localhost:3000/api/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5MzE4NTkxLWJlOTEtNDc3Mi05Y2VjLTA2MGZmZGQ4OTMxZiIsIm5hbWUiOiJKb3JkYW4gTWF1bGFuYSIsImVtYWlsIjoiam9yZGFuQGdtYWlsLmNvbSIsImlhdCI6MTcwNDE4MDE4NCwiZXhwIjoxNzA0Nzg0OTg0fQ.ly6YSaEYNzJv9BFL5B6NlMAA7HBKQpx6H87B_F6Nqgw

### Get single links

GET http://localhost:3000/api/links/399a366c-337b-4e67-8145-ceb2fc80d845

### Update link

PATCH http://localhost:3000/api/links/399a366c-337b-4e67-8145-ceb2fc80d845

{
    "isActive" : false
}


### Delete link

DELETE http://localhost:3000/api/links/c7281605-f65f-4c24-abb6-2a6ed8b2eabb
